### ISSUE TITLE
Product name doesn't display in cart if default option is chosen

### ISSUE THREAD

**Issue by rachgo** [bigcartel-themes/sexy#18]
If the default option is selected > added to cart, it just shows the option name and not the product name + option (ex: http://www.thelostcause.bigcartel.com/product/no-one-gives-a-fuck-tee-pre-sale size small shows just 'S' in the cart, but the other options show product name + size option in cart)

![screen shot 2015-02-18 at 10 37 23 am](https://cloud.githubusercontent.com/assets/3578349/6251567/357baa98-b75a-11e4-8513-002144d622be.png)

This store is using seamless, newest default Sexy (Gold plan)

**Comment by nickendle** [comment]
@rachgo this is all fixed, if it's still happening to anyone just re-save their settings or their theme and it'll be good to go
