### ISSUE TITLE
Product name/thumbnail overlap issue in Firefox

### ISSUE THREAD

**Issue by rachgo** [bigcartel-themes/sexy#19]
Can duplicate this in the latest version of Firefox:

![firefox v38 0](https://cloud.githubusercontent.com/assets/3578349/7691764/c990eff4-fd82-11e4-802f-deedff45150c.gif)

http://bmdcnv.bigcartel.com

**Comment by nickendle** [comment]
looks like this was a result of customizing their CSS.. closing.
